services:
  web:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: ${PROJECT_PREFIX}-web
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ../web:/var/www/html
      - ./volumes/log/apache2:/var/log/apache2
      - ./volumes/log/php:/var/log/php
      - ./volumes/etc/apache.conf:/etc/apache2/conf-enabled/custom.conf
      - ./volumes/etc/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - ./volumes/share:/mnt/share
    networks:
      - local_network
  db:
    image: mysql:8.0
    container_name: ${PROJECT_PREFIX}-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./volumes/log/mysql:/var/log/mysql
      - ./volumes/data:/var/lib/mysql
      - ./volumes/share:/mnt/share
    networks:
      - local_network
networks:
  local_network:
    driver: bridge
